Fix: Top SAM crashes
aws/serverless-application-model pull request #1671
Opened 2020-07-29 19:53 UTC by prenx4x

*Issue #, if available:*

*Description of changes:*
Fixed some common SAM crashes

*Description of how you validated changes:*
Changes validated using unit tests

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-07-31 15:33 UTC, jfuss commented on samtranslator/swagger/swagger.py
> +                            ["Invalid entry {security} in 'security'".format(security=security)]
Why is it invalid?

2020-07-31 15:33 UTC, jfuss commented on samtranslator/swagger/swagger.py
> +                raise InvalidDocumentException(["Invalid input. Value for properties is required"])
Same here

2020-07-31 15:35 UTC, jfuss commented on samtranslator/swagger/swagger.py
> +            raise InvalidDocumentException(["Invalid resource policy"])
Make sure to provide some details about where this is in the template. We generally do this through adding the logical id, so the customer at least knows what resource they need to dig into. This goes for all the exceptions, not just this one.

2020-10-21 17:00 UTC, jfuss requested changes
Can we add additional test cases in `test_transform_invalid_document` to verify we have fixed the issue.

2020-10-27 19:34 UTC, prenx4x commented
We can close this PR as I am breaking it in favor of #1757 and others to come.

2020-10-27 21:12 UTC, closed without merging