feature: Support MTLS auth properties in REST and HTTP API domain names
aws/serverless-application-model pull request #1725
Opened 2020-09-28 15:06 UTC by wchengru

*Issue #, if available:*

*Description of changes:*

*Description of how you validated changes:*

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-09 23:01 UTC, awood45 requested changes
Generally looks good, a few comments.

2020-10-09 23:01 UTC, awood45 commented on samtranslator/model/api/api_generator.py
> +            if mutual_tls_auth.get("TruststoreUri", None):
We should add an exception if we get any keys that are not covered by these cases, to avoid failing open on a typo, for example.

2020-10-09 23:01 UTC, awood45 commented on samtranslator/model/api/http_api_generator.py
> +        if mutual_tls_auth and isinstance(mutual_tls_auth, dict):
Same comments as above.

2020-10-13 18:29 UTC, wchengru commented on samtranslator/model/api/api_generator.py
> +        if mutual_tls_auth and isinstance(mutual_tls_auth, dict):
Added exception in case this one is not a dict, and also valid the two fields are correct.

2020-10-20 00:02 UTC, awood45 approved these changes

2020-10-20 00:12 UTC, merged