Added StepFunctionSyncExecutionPolicy to support StartSyncExecution for SFN express workflows.
aws/serverless-application-model pull request #1984
Opened 2021-04-09 06:31 UTC by avladi

*Issue #, if available:*

*Description of changes:* Added "StepFunctionsSyncExecutionPolicy" policy to add support for synchronous execution of SFN express workflows.

*Description of how you validated changes:*
The policy is based on existing one for the StepFunction. The only difference is Action StartSyncExecution. I triple checked file formats.

*Checklist:*

- [x] Write/update tests
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*
```yaml
  StartSyncSFNExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartSyncSFNExpressFunctionName
      CodeUri: ../Lambdas/StartSyncSFNExpressFunction
      Handler: StartSyncSFNExpressFunction.StartExecution
      Runtime: python3.8
      Policies:
        - StepFunctionsSyncExecutionPolicy:
            StateMachineName: !GetAtt TestStepFunction.Name
```

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-09 06:52 UTC, avladi commented
I checked failed build, I do not see anything wrong. I updated all documents where existing StepFunction policy is defined. I will try to run the failed test locally tomorrow.

2021-04-13 18:51 UTC, avladi commented
The build is fixed, waiting for the review

2022-03-31 03:35 UTC, hawflau approved these changes
The change makes sense to me. We will request a security review internally as the change involves IAM policy changes.

2022-03-31 03:47 UTC, hawflau requested changes

2022-03-31 03:47 UTC, hawflau commented on samtranslator/policy_templates_data/policy_templates.json
> +    "StepFunctionsSyncExecutionPolicy": {
Can we have a better name that mentions it is for Synchronous Express Workflows? It is also using the same name as in PR #1622 which covers the [standard synchronous workflow](https://docs.aws.amazon.com/step-functions/latest/dg/stepfunctions-iam.html#synchronous).

2022-06-13 18:00 UTC, hawflau commented
Closing due to inactivity. Please open a new PR with the suggested change when it's ready. Thanks

2022-06-13 18:00 UTC, closed without merging