Add StepFunctionsListExecutionPolicy
aws/serverless-application-model pull request #2028
Opened 2021-05-15 03:10 UTC by ihalder1

This policy will allow Lambda functions to list executions of a Step function

*Issue #, if available:*

*Description of changes:*

*Description of how you validated changes:*

*Checklist:*

- [ ] Write/update tests
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-15 23:35 UTC, ihalder1 commented
> perform readonly operation in state machine execution

2021-05-15 23:37 UTC, ihalder1 commented
> # [Codecov](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws) Report
> > Merging [#2028](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws) ([f3ae41b](https://github.com/aws/serverless-application-model/commit/f3ae41b37f6a5a0a5c4258800a6bd4b478ad7703)) into [develop](https://codecov.io/gh/aws/serverless-application-model/commit/54e2a160e182dafcc90399f6af58a1a29dd06f37?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws) ([54e2a16](https://github.com/aws/serverless-application-model/commit/54e2a160e182dafcc90399f6af58a1a29dd06f37)) will **increase** coverage by `0.04%`.
> > The diff coverage is `n/a`.
> 
> [![Impacted file tree graph](https://camo.githubusercontent.com/b2fe2d8c2c0a692bc4dd942079a2b4b75d67bc0253b4c4470afaaa1b14bf96da/68747470733a2f2f636f6465636f762e696f2f67682f6177732f7365727665726c6573732d6170706c69636174696f6e2d6d6f64656c2f70756c6c2f323032382f6772617068732f747265652e7376673f77696474683d363530266865696768743d313530267372633d707226746f6b656e3d397176326364625833382675746d5f6d656469756d3d726566657272616c2675746d5f736f757263653d6769746875622675746d5f636f6e74656e743d636f6d6d656e742675746d5f63616d706169676e3d70722b636f6d6d656e74732675746d5f7465726d3d617773)](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws)
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop    #2028      +/-   ##
> ===========================================
> + Coverage    93.58%   93.63%   +0.04%     
> ===========================================
>   Files           90       90              
>   Lines         6080     6080              
>   Branches      1247     1247              
> ===========================================
> + Hits          5690     5693       +3     
> + Misses         182      180       -2     
> + Partials       208      207       -1     
> ```
> 
> [Impacted Files](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws)	Coverage Δ	
> [samtranslator/translator/logical_id_generator.py](https://codecov.io/gh/aws/serverless-application-model/pull/2028/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws#diff-c2FtdHJhbnNsYXRvci90cmFuc2xhdG9yL2xvZ2ljYWxfaWRfZ2VuZXJhdG9yLnB5)	`100.00% <0.00%> (+9.09%)`	⬆️
> [Continue to review full report at Codecov](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws). Last update [54e2a16...f3ae41b](https://codecov.io/gh/aws/serverless-application-model/pull/2028?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=aws).

2021-05-15 23:38 UTC, ihalder1 reviewed
All good

2021-05-15 23:40 UTC, ihalder1 commented
reopen

2021-05-17 04:25 UTC, ihalder1 commented
@szilveszter @pfeilbr @me2resh Can you please review and update the pull request.

2021-05-20 20:17 UTC, hoffa approved these changes

2021-05-20 22:48 UTC, ihalder1 commented
Thanks @hoffa for approving the pull request. @pfeilbr and @szilveszter this pull request need one more approval, can one of you please review and do the necessary.

2021-05-27 00:00 UTC, ihalder1 commented
HI @szilveszter please review and approve this change

2021-05-27 07:35 UTC, szilveszter commented
@ihalder1 I'm sorry, I'm just another random contributor to this project, and don't have commit rights, so I don't think my review counts.

2021-07-04 22:39 UTC, wchengru requested changes

2021-07-04 22:39 UTC, wchengru commented on samtranslator/policy_templates_data/policy_templates.json
> +                "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${stateMachineName}",
Hi @ihalder1 , the arns for activities, executions and statemachines are different ([doc](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsstepfunctions.html#awsstepfunctions-resources-for-iam-policies)). Can you please add the resources and verify them?

2022-03-31 03:09 UTC, hawflau commented
Closing the PR as there is no response for a while. Feel free to re-open and ask for approval again after addressing the change request. As @wchengru mentioned, the resource do not apply to all permissions in the policy template.

2022-03-31 03:09 UTC, hawflau commented
Closing the PR as there is no response for a while. Feel free to re-open and ask for approval again after addressing the change request. As @wchengru mentioned, the resource do not apply to all permissions in the policy template.

2022-03-31 03:09 UTC, closed without merging