Fix multiple segments in BasePath
aws/serverless-application-model pull request #2041
Opened 2021-05-20 06:27 UTC by agrippa1994

*Issue #, if available:*
None

*Description of changes:*
The API gateway supports multiple segments in the base path mappings like specified in this [repository](https://github.com/aws-samples/sessions-with-aws-sam/blob/master/multi-level-mapping/reportingv1.yaml#L21). However, whenever a ```BasePath``` with multiple segments is specified in a ```AWS::Serverless::HttpApi``` (see examples below), then the template does not contain these multiple segments after the transformation anymore.

```yaml
# SAM Template:
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: somedomain.com
        CertificateArn: some-certificate-arn
        BasePath:
          - "api/v1"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: some-hosted-zone
```
```json
// transformed template
"HttpApiapiApiMapping": {
  "Type": "AWS::ApiGatewayV2::ApiMapping",
  "Properties": {
    "ApiId": {
      "Ref": "HttpApi"
    },
    "ApiMappingKey": "api",
    "DomainName": {
      "Ref": "ApiGatewayDomainNameV2dc0129008b"
    },
    "Stage": {
      "Ref": "HttpApiApiGatewayDefaultStage"
    }
  }
}
```
The implementation fixes the regex that strips trailing and leading forward slashes (the segments). After that, the transformed template looks as following example:
```json
// transformed template
"HttpApiapiv1ApiMapping": {
  "Type": "AWS::ApiGatewayV2::ApiMapping",
  "Properties": {
    "ApiId": {
      "Ref": "HttpApi"
    },
    "ApiMappingKey": "api/v1",
    "DomainName": {
      "Ref": "ApiGatewayDomainNameV2dc0129008b"
    },
    "Stage": {
      "Ref": "HttpApiApiGatewayDefaultStage"
    }
  }
},
```

*Description of how you validated changes:*
I used my SAM template with a ```BasePath``` with multiple segments. After transformation and deployment, the ApiMappingKey was correct for my Domain.

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [x] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-20 18:04 UTC, hoffa commented
Thanks for the PR! Likely related: https://github.com/aws/serverless-application-model/pull/2041

2021-05-20 19:25 UTC, hoffa approved these changes

2021-06-04 18:58 UTC, c2tarun approved these changes

2021-06-04 20:23 UTC, mgrandis commented on samtranslator/model/api/http_api_generator.py
> +                    path = re.sub(r"^/+|/+$", "", path)
I think we could replace the whole `if / else` by a `path.strip("/")`

2021-06-04 20:58 UTC, mgrandis commented on tests/model/api/test_http_api_generator.py
> +            "BasePath": ["one-1", "two_2", "three", "/", "api/v1"],
We should add: `"/api"`, `"api/v1/"`, `"/api/v1/"` cases to test the `/` stripping.

2021-06-04 23:03 UTC, mgrandis requested changes
Just a few remarks

2021-06-14 05:35 UTC, agrippa1994 commented
Thanks for your review. I'm going to fix them as soon as I have some time for doing that.

2021-06-22 07:01 UTC, agrippa1994 commented
@mgrandis I have implemented your requested changes. The stripping method works perfectly fine here.

2021-06-22 16:14 UTC, mgrandis commented on samtranslator/model/api/http_api_generator.py
> +                    path = path.strip("/")
I think you can actually replace the whole if/else.
if `path == "/"`, `path.strip("/")` will result in `""`.
So you can replace the whole L343-L347 with `path = path.strip("/")`

2021-06-23 15:38 UTC, mgrandis approved these changes

2021-09-17 01:06 UTC, merged