validate Http Api Authorizers identity Header
aws/serverless-application-model pull request #2339
Opened 2022-03-07 21:50 UTC by jonife

*Issue #, if available:*

*Description of changes:*
added validation to validate the property type of Authorizers Identity parameter Headers to arrest a situation where an intrinsic value can't be resolved.

*Description of how you validated changes:*
created a test sam template and tested the exception

*Checklist:*

- [x] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [x] Correct values
    - [x] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [x] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-22 20:16 UTC, mildaniel approved these changes

2022-03-22 20:24 UTC, hoffa commented on samtranslator/model/apigatewayv2.py
> +                headers = self.identity.get("Headers")
To prevent the duplication:

```suggestion
            headers = self.identity.get("Headers")
            if headers:
```

2022-03-31 23:45 UTC, hawflau requested changes

2022-03-31 23:45 UTC, hawflau commented on samtranslator/model/apigatewayv2.py
> +                raise InvalidResourceException(
Can you also add a test case to test this branch?

2022-04-19 23:28 UTC, moelasmar commented
@jonife .. could you please resolve the merge conflicts.

2022-06-07 23:40 UTC, hawflau approved these changes

2022-06-07 23:40 UTC, merged