fix: Add retries to SAR service calls on throttle
aws/serverless-application-model pull request #2352
Opened 2022-03-16 16:25 UTC by mildaniel

*Issue #, if available:*

*Description of changes:*

*Description of how you validated changes:*

*Checklist:*

- [x] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [ ] Correct values
    - [ ] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [x] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-16 16:28 UTC, mildaniel commented on samtranslator/plugins/__init__.py
> -    """
Move this to a separate file to resolve a circular dependency.
`samtranslator.plugins (__init__.py)` -> `samtranslator.model.exceptions…` -> `samtranslator.plugins.LifeCycleEvents`

2022-03-25 16:19 UTC, hawflau requested changes

2022-03-25 16:19 UTC, hawflau commented on samtranslator/plugins/application/serverless_app_plugin.py
> +        while (time() - start_time) < self.TEMPLATE_WAIT_TIMEOUT_SECONDS:
There's also a similar retry pattern used in `on_after_transform_template`. I can see things are done a bit differently within this retry and that retry. But can we try to refactor the retry part into a decorator that can be used on both?

2022-04-01 22:01 UTC, moelasmar approved these changes

2022-04-01 23:34 UTC, hawflau approved these changes

2022-04-04 16:15 UTC, merged