Furl AutopublishAlias bug fix
aws/serverless-application-model pull request #2378
Opened 2022-04-13 17:25 UTC by jonife

*Issue #, if available:*

*Description of changes:*

*Description of how you validated changes:*

*Checklist:*

- [ ] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [ ] Correct values
    - [ ] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-14 01:31 UTC, mndeveci requested changes
Thanks for the PR @jonife .

Can we check the following failure?
```
FAILED tests/model/api/test_http_api_generator.py::TestHttpApiGenerator::test_enabling_auth_iam_does_not_clobber_conflicting_custom_authorizer - samtranslator.model.exceptions.InvalidResourceException: ('HttpApiId', "Specify either 'Defi...
```

And also, will this require any documentation change?

2022-04-20 12:31 UTC, jfuss approved these changes
LGTM, only question is are there integration tests we need to update with these? We recently adding python integration tests in the repo and want to make sure we have the correct coverage.

2022-04-20 21:14 UTC, jonife commented
> LGTM, only question is are there integration tests we need to update with these? We recently adding python integration tests in the repo and want to make sure we have the correct coverage.

can't seem to think of any one of the top of my head, i think the integration test covers everything

2022-04-22 16:37 UTC, mndeveci approved these changes

2022-04-22 16:42 UTC, hawflau commented
> > LGTM, only question is are there integration tests we need to update with these? We recently adding python integration tests in the repo and want to make sure we have the correct coverage.
> 
> can't seem to think of any one of the top of my head, i think the integration test covers everything

Should we test calling the Function URL to confirm if the Lambda Function Alias is invoked without any error? From what I understand, the integration test for FURL does not make any call to the created FURL.

2022-05-19 21:35 UTC, hawflau commented
note: we will submit another PR to address the integration tests

2022-05-19 21:35 UTC, merged