Add ability to set State of EventBridge Rule
aws/serverless-application-model pull request #2524
Opened 2022-10-10 23:28 UTC by sebastiankasprzak

*Issue #, if available:*
#2509 

*Description of changes:*

- Added a schema and test to support `State` property of `AWS::Events::Rule` in SAM

*Description of how you validated changes:*
Used `bin/sam-translate.py` to generate a CFN template from SAM template which I then successfully deployed in my AWS account with desired changes taking effect.

*Checklist:*

- [X] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [X] Correct values
    - [ ] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [X] `make pr` passes
- [ ] Update documentation
- [X] Verify transformed template deploys and application functions as expected
- [ ] Do these changes include any template validations?
    - [ ] Did the newly validated properties support intrinsics prior to adding the validations? (If unsure, please review [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) before proceeding).
        - [ ] Does the pull request ensure that intrinsics remain functional with the new validations?

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-11 17:55 UTC, aahung requested changes
Thanks!

there are couple of places to change to add to the property dict:

https://github.com/aws/serverless-application-model/blob/21545a2d10becb2837dd825b47f7f9860750c640/samtranslator/model/eventsources/push.py#L273

https://github.com/aws/serverless-application-model/blob/21545a2d10becb2837dd825b47f7f9860750c640/samtranslator/model/stepfunctions/events.py#L240

2022-10-11 17:57 UTC, aahung commented
@sebastiankasprzak can we also update the transform tests (both SFN and Lambda event source to include this new property?

2022-10-11 23:29 UTC, sebastiankasprzak commented
> 

So Lambda Event source already had the `State` method implemented:
https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L190
https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L226

I'll add `State` property to SFN and add test to it 👍

2022-10-12 04:16 UTC, sebastiankasprzak commented on tests/model/eventsources/test_eventbridge_rule_source.py
> +        self.assertEqual(state, "Disabled")
changed it to capitals 👍

2022-10-12 04:49 UTC, sebastiankasprzak commented
@aahung those changes are now be implemented. I have not added integration tests, how would you recommend these should be added?

2022-10-12 07:49 UTC, aahung submitted a review, later dismissed
LGTM! Thanks for addressing the comments!

2022-10-12 07:52 UTC, aahung reviewed
One more comment: It would be great if we can use the new "State" in our transform tests, e.g., [here](https://github.com/aws/serverless-application-model/blob/971c6bb3d020c50919056deaf1d1b9cb9b02f05f/tests/translator/input/eventbridgerule_with_dlq.yaml#L24), you can run make test to verify if it translates to the current template.

2022-10-13 05:14 UTC, sebastiankasprzak commented
nice! Added transform test for one of the Eventbridge tests. Let me know if that's good enough

2022-10-13 22:52 UTC, aahung approved these changes
LGTM! Thanks for addressing the comments

2022-10-13 23:04 UTC, awood45 approved these changes

2022-10-13 23:11 UTC, merged