Add Connector from Lambda to QLDB
aws/serverless-application-model pull request #2918
Opened 2023-02-17 00:20 UTC by awood45

Addresses and replaces #2003

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-17 00:42 UTC, hoffa commented on integration/resources/templates/combination/connector_function_to_qldb_read.yaml
> +Resources:
Can you add these as transform tests as well?

```bash
python bin/add_transform_test.py --template-file integration/resources/templates/combination/connector_function_to_qldb_read.yaml
python bin/add_transform_test.py --template-file integration/resources/templates/combination/connector_function_to_qldb_write.yaml
```

2023-02-17 00:47 UTC, acristin requested changes
I think you need to add a QLDB item [here](https://github.com/aws/serverless-application-model/blob/13604cd2d9671cd6e774e5bfd610a03d82a08d76/integration/helpers/resource.py#L212)

2023-02-17 00:50 UTC, acristin approved these changes

2023-02-17 00:52 UTC, hoffa approved these changes

2023-02-17 01:20 UTC, ssenchenko approved these changes

2023-02-22 18:52 UTC, GavinZZ approved these changes

2024-01-08 18:35 UTC, closed without merging